version: "3.8"
services:
  mysql:
    image: mysql
    container_name: mysql_tasks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tasks
      MYSQL_USER: user_tasks
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
  test-db:
    image: mysql
    container_name: test_mysql_tasks_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test_tasks
      MYSQL_USER: user_test_tasks
      MYSQL_PASSWORD: root 
